apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: git-ref
      value: $(body.ref)
    - name: git-branch
      value: $(body.ref.replace('refs/heads/', ''))
