apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: tekton
  app.kubernetes.io/part-of: sample-camel

images:
  - name: sample-camel
    newTag: latest
