apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sample-camel-build-
  labels:
    app.kubernetes.io/name: sample-camel
    tekton.dev/pipeline: universal-build
spec:
  pipelineRef:
    name: universal-build
  serviceAccountName: pipeline-runner
  params:
    - name: git-url
      value: https://github.com/rmallam/openshift-pipelines-examples.git
    - name: git-revision
      value: main
    - name: git-subdirectory
      value: apps/sample-camel
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/sample-camel-dev/sample-camel:latest
    - name: dockerfile
      value: ./Dockerfile
    - name: context
      value: apps/sample-camel
    - name: test-type
      value: maven
    - name: test-goals
      value:
        - test
    - name: test-subdirectory
      value: apps/sample-camel
    - name: tls-verify
      value: "false"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace-pvc
    - name: docker-credentials
      emptyDir: {}
