apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sample-camel-sync-argocd-dev-
  labels:
    app.kubernetes.io/name: sample-camel
    app.kubernetes.io/environment: dev
    tekton.dev/pipeline: universal-deploy
spec:
  pipelineRef:
    name: universal-deploy
  serviceAccountName: pipeline-runner
  taskRunSpecs:
    - pipelineTaskName: sync-argocd
      podTemplate:
        env:
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: argocd-token
                key: token
  params:
    - name: git-url
      value: https://github.com/rmallam/openshift-pipelines-examples.git
    - name: deploy-mode
      value: argocd
    - name: deploy-path
      value: deploy/kustomize/overlays/dev
    - name: target-namespace
      value: sample-camel-dev
    - name: argocd-app-name
      value: sample-camel-dev
    - name: wait-for-rollout
      value: "true"
  workspaces:
    - name: shared-workspace
      emptyDir: {}
    - name: kubeconfig
      emptyDir: {}
