replicaCount: 1

image:
  repository: sample-camel
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

route:
  enabled: false
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  path: /api/hello
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20

environment: dev
