replicaCount: 1

image:
  repository: IMAGE_PLACEHOLDER
  tag: latest

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

route:
  enabled: false

environment: dev
