apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/component: operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tekton
  source:
    repoURL: https://github.com/rmallam/openshift-pipelines-examples.git
    targetRevision: main
    path: operators/openshift-pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      jsonPointers:
        - /status
