apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/component: cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tekton
  source:
    repoURL: https://github.com/rmallam/openshift-pipelines-examples.git
    targetRevision: main
    path: pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: tekton.dev
      kind: PipelineRun
      jsonPointers:
        - /status
