apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-camel
spec:
  to:
    kind: Service
    name: sample-camel
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
